name: Deploy Lambda Function to AWS

on:
  push:
    branches:
      - main

env:
  LAMBDA_FUNCTION_NAME: precos-pmc-lambda-load-to-landing

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Package Lambda
        run: |
          cd src
          zip -r ../function.zip .

      - name: Inspect ZIP
        run: unzip -l function.zip

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --zip-file fileb://function.zip